package net.echo.hypermixins.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.MethodSpec
import com.squareup.javapoet.TypeSpec
import java.io.OutputStreamWriter
import javax.lang.model.element.Modifier

/**
 * Per-mixin payload collected by {@link MixinSymbolProcessor#processMixin} and consumed by
 * {@link DescriptorEmitter#emit}. Lives at file level so the emitter and the orchestrator do
 * not need to share an 18-parameter call signature.
 */
internal data class MixinHarvest(
    val mixinClass: KSClassDeclaration,
    val targetClass: String,
    val overwrites: List<OverwriteEntry>,
    val originals: List<OriginalEntry>,
    val redirects: List<RedirectEntry>,
    val injects: List<InjectEntry>,
    val injectLocals: List<InjectLocalEntry>,
    val shadows: List<ShadowEntry>,
    val shadowFields: List<ShadowFieldEntry>,
    val shadowStaticFields: List<ShadowFieldEntry>,
    val modifyRvs: List<ModifyReturnValueEntry>,
    val modifyConsts: List<ModifyConstantEntry>,
    val modifyArgs: List<ModifyArgEntry>,
    val modifyExprs: List<ModifyExpressionValueEntry>,
    val modifyArgsList: List<ModifyArgsEntry>,
    val modifyReceivers: List<ModifyReceiverEntry>,
    val accessors: List<AccessorEntry>,
    val invokers: List<InvokerEntry>,
    val staticTargets: Set<String>,
    val privateShadowTargets: Set<String>,
)

internal data class EmitResult(
    val descriptorFqn: String,
    val mixinFqn: String,
    val containingFile: KSFile?,
)

/**
 * Generates one $$Descriptor Java class per @Mixin, emitting the 18 entries* accessors plus
 * the mixinClass / targetClass / syntheticNames metadata. Pure JavaPoet over a [MixinHarvest];
 * no KSP iteration logic, no validation.
 */
internal class DescriptorEmitter(private val codeGenerator: CodeGenerator) {

    fun emit(h: MixinHarvest): EmitResult? {
        val mixinFqn = h.mixinClass.qualifiedName?.asString() ?: return null
        val descriptorFqn = "$mixinFqn\$\$Descriptor"
        val pkg = if ('.' in descriptorFqn) descriptorFqn.substringBeforeLast('.') else ""
        val simpleName = descriptorFqn.substringAfterLast('.')

        val classBuilder = TypeSpec.classBuilder(simpleName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addJavadoc("Generated by HyperMixins KSP processor. Do not edit.")

        classBuilder.addMethod(stringConst("mixinClass", mixinFqn))
        classBuilder.addMethod(stringConst("targetClass", h.targetClass.replace('.', '/')))

        classBuilder.addMethod(entriesMethod("overwriteEntries", h.overwrites.map {
            arrayOf(it.targetName, it.targetDesc, it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("originalEntries", h.originals.map {
            arrayOf(it.handlerName, it.handlerDesc, it.targetName)
        }))
        classBuilder.addMethod(entriesMethod("redirectEntries", h.redirects.map {
            arrayOf(it.targetMethod, it.invokeDesc, it.index.toString(), it.call, it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("injectEntries", h.injects.map {
            arrayOf(it.targetMethod, it.point, it.atDesc, it.atIndex.toString(),
                it.cancellable.toString(), it.returnable.toString(), it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("injectShifts",
            h.injects.filter { it.shift == "AFTER" }.map { arrayOf(it.handlerName, it.handlerDesc, it.shift) }))
        classBuilder.addMethod(entriesMethod("injectCaptureLocals", h.injectLocals.map {
            arrayOf(it.handlerName, it.handlerDesc, it.paramIndex.toString(), it.slot.toString(), it.ordinal.toString(), it.argsOnly.toString())
        }))
        classBuilder.addMethod(entriesMethod("shadowEntries", h.shadows.map {
            arrayOf(it.handlerName, it.handlerDesc, it.targetName)
        }))
        classBuilder.addMethod(entriesMethod("shadowFieldEntries", h.shadowFields.map {
            arrayOf(it.mixinFieldName, it.fieldDesc, it.targetFieldName)
        }))
        classBuilder.addMethod(entriesMethod("shadowStaticFieldEntries", h.shadowStaticFields.map {
            arrayOf(it.mixinFieldName, it.fieldDesc, it.targetFieldName)
        }))
        classBuilder.addMethod(entriesMethod("modifyReturnValueEntries", h.modifyRvs.map {
            arrayOf(it.targetMethod, it.invokeDesc, it.index.toString(), it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("accessorEntries", h.accessors.map {
            arrayOf(it.handlerName, it.handlerDesc, it.kind, it.targetField)
        }))
        classBuilder.addMethod(entriesMethod("invokerEntries", h.invokers.map {
            arrayOf(it.handlerName, it.handlerDesc, it.targetName)
        }))
        classBuilder.addMethod(entriesMethod("modifyConstantEntries", h.modifyConsts.map {
            arrayOf(it.targetMethod, it.type, it.value, it.index.toString(), it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("modifyArgEntries", h.modifyArgs.map {
            arrayOf(it.targetMethod, it.invokeDesc, it.argIndex.toString(), it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("modifyExpressionValueEntries", h.modifyExprs.map {
            arrayOf(it.targetMethod, it.point, it.atDesc, it.index.toString(), it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("modifyArgsEntries", h.modifyArgsList.map {
            arrayOf(it.targetMethod, it.invokeDesc, it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("modifyReceiverEntries", h.modifyReceivers.map {
            arrayOf(it.targetMethod, it.invokeDesc, it.handlerName, it.handlerDesc)
        }))
        classBuilder.addMethod(entriesMethod("staticTargetMethods", h.staticTargets.map {
            val paren = it.indexOf('(')
            arrayOf(it.substring(0, paren), it.substring(paren))
        }))
        classBuilder.addMethod(entriesMethod("privateShadowTargetMethods", h.privateShadowTargets.map {
            val paren = it.indexOf('(')
            arrayOf(it.substring(0, paren), it.substring(paren))
        }))
        classBuilder.addMethod(entriesMethod("syntheticNames", h.overwrites.map {
            arrayOf(
                it.targetName, it.targetDesc,
                NameMangling.mangledOriginalName(it.targetName, it.targetDesc),
                NameMangling.dispatchName(it.targetName, it.targetDesc)
            )
        }))

        val file = JavaFile.builder(pkg, classBuilder.build()).build()
        val out = codeGenerator.createNewFile(
            Dependencies(false, h.mixinClass.containingFile!!),
            pkg, simpleName, "java"
        )
        OutputStreamWriter(out).use { file.writeTo(it) }
        return EmitResult(descriptorFqn, mixinFqn, h.mixinClass.containingFile)
    }

    private fun stringConst(name: String, value: String): MethodSpec =
        MethodSpec.methodBuilder(name)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .returns(String::class.java)
            .addStatement("return \$S", value)
            .build()
}
