package net.echo.hypermixins.agent;

import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.InsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;
import org.objectweb.asm.tree.VarInsnNode;

import java.util.Arrays;

/**
 * Rewrites every {@code @Original}-annotated method in the mixin class into a trampoline that
 * invokes the corresponding {@code __original$<name>$<hash>} synthetic generated by
 * {@link OverwritePass#apply} on the target. Strips ACC_NATIVE so the original
 * declaration can be source-only and still produce a callable body at runtime.
 */
final class OriginalPass {

    private OriginalPass() {}

    static void apply(ClassNode node, MixinMapping mapping) {
        for (MethodNode method : node.methods) {
            String key = method.name + method.desc;
            if (!mapping.getOriginals().containsKey(key)) continue;

            Type[] args = Type.getArgumentTypes(method.desc);
            if (args.length == 0) {
                throw new IllegalStateException(
                    "@Original method must declare Object self as first parameter: " + method.name + method.desc);
            }

            Type returnType  = Type.getReturnType(method.desc);
            Type[] targetArgs = Arrays.copyOfRange(args, 1, args.length);
            String targetDesc = Type.getMethodDescriptor(returnType, targetArgs);

            if ((method.access & Opcodes.ACC_NATIVE) != 0) method.access &= ~Opcodes.ACC_NATIVE;
            method.instructions.clear();
            method.tryCatchBlocks.clear();
            method.localVariables = null;

            String mappedTarget  = mapping.getTargetClass().replace('.', '/');
            String targetName    = mapping.getOriginals().get(key);
            String[] synths      = mapping.descriptor().synthetics().get(targetName + targetDesc);
            if (synths == null) {
                throw new IllegalStateException(
                    "Missing precomputed synthetic names for @Original target " + targetName + targetDesc);
            }
            String originalName  = synths[0];
            boolean targetIsStatic = mapping.descriptor().isStaticTargetMethod(targetName, targetDesc);

            InsnList insns = new InsnList();
            int slot;
            if (!targetIsStatic) {
                insns.add(new VarInsnNode(Opcodes.ALOAD, 1));
                insns.add(new TypeInsnNode(Opcodes.CHECKCAST, mappedTarget));
            }
            slot = 2;
            for (Type arg : targetArgs) {
                insns.add(new VarInsnNode(arg.getOpcode(Opcodes.ILOAD), slot));
                slot += arg.getSize();
            }
            insns.add(new MethodInsnNode(
                targetIsStatic ? Opcodes.INVOKESTATIC : Opcodes.INVOKEVIRTUAL,
                mappedTarget, originalName, targetDesc, false));
            insns.add(new InsnNode(returnType.getOpcode(Opcodes.IRETURN)));
            method.instructions.add(insns);
        }
    }
}
